services:
  pocketsmart:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: sqlite:///./pocketsmart_data/pocketsmart.db
    env_file:
      - .env
    volumes:
      - ./pocketsmart_data:/app/pocketsmart_data
